[[ce.tutorial]]
== Getting Started with Collaboration Engine
:sectnums:

This tutorial shows basic steps to set up Collaboration Engine in your Vaadin project
and add the following collaboration features to a simple form:

* Users can see the avatars of all the users who are currently present in the app
* When someone enters a new value to a field, it will be propagated to all users
* Users can see who is currently editing each field (a feature referred to as field highlight)

[[ce.tutorial.setup]]
=== Prepare the Application

==== Set Up a Vaadin Project
Download an empty Vaadin 14 project from https://vaadin.com/start/v14
using any technology stack.

==== Update Project Dependencies
In the project's pom.xml file, add the `vaadin-prerelease` repository:
[source, xml]
----
<repository>
    <id>vaadin-prereleases</id>
    <url>https://maven.vaadin.com/vaadin-prereleases</url>
    <releases>
        <enabled>true</enabled>
    </releases>
    <snapshots>
        <enabled>true</enabled>
    </snapshots>
</repository>
----
add Collaboration Engine as a dependency:
[source, xml]
----
<dependency>
    <groupId>com.vaadin</groupId>
    <artifactId>collaboration-engine</artifactId>
    <version>[[version]]</version>
</dependency>
----
Consult the releases page to find the version number of the latest release, e.g. `1.0.0.alpha2`.
The latest version of this tutorial might use functionality that is only available in the latest snapshot build, i.e. `1.0-SNAPSHOT`.
You can use the branch selector in the GitHub UI to view the tutorial that corresponds to a specific release tag.

[[ce.tutorial.add-collaborative-feature]]
=== Add Collaboration Features
This tutorial will build a form where the users can edit the name and
date of birth of a person. Let's start by adding the `Person` bean class.

[source, java]
----
public class Person {
    private String name;
    private LocalDate dateOfBirth;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public LocalDate getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
}
----

==== Create a Simple View

To start writing the actual application, create a view with a text field
and a date picker but not yet any collaborative functionality.
The view is annotated with `@Push` so that the server can push updates from one user to the others.

[source, java]
----
@Push
@Route("")
public class TutorialView extends VerticalLayout {

    public TutorialView() {
        TextField nameField = new TextField("Name");
        DatePicker dateOfBirthField = new DatePicker("Date of birth");
        add(nameField, dateOfBirthField);
    }
}
----

==== Provide User Information

The `UserInfo` class represents an end user of a collaborative application.
It has properties such as `name` and `image`, which will be used to display
information of who is currently present in the view or editing a field.

In a real application, this kind of profile information should come from the
application's backend based on the currently logged in user.
For the sake of this tutorial, let's just use the same hard-coded name for
each user. Let's also generate a random UUID as the unique user identifier
(required by the `UserInfo` constructor).
[source, java]
----
UserInfo localUser = new UserInfo(UUID.randomUUID().toString());
localUser.setName("Jon Doe");
----
The name will be displayed to other users when editing a field, and
the user's avatar will contain the abbreviation of the name (as we don't
provide a user image in this example).

NOTE: `UserInfo` has also a `colorIndex` property. It defines which color will be
used in the user's avatar as well as in the field highlight when editing a field.
This property is generated automatically based on the user id by default, so we
don't have to set it explicitly.

==== Add User Avatars

To display the avatars of all users who are currently in the application,
create a `CollaborationAvatarGroup` component.

[source, java]
----
CollaborationAvatarGroup avatarGroup = new CollaborationAvatarGroup(
        localUser, "tutorial");
addComponentAsFirst(avatarGroup);
----

First of all, the components needs our local users information (the `UserInfo`
object which we created earlier), to know how to render the user's avatar.

As a second constructor argument, the component needs a topic id.
Collaboration Engine propagates information only within the group that is
connected to the same topic.
In our case, there's only one topic to work on, so we can use any hardcoded topic id.

NOTE: If we'd expand our application so that there would be multiple editable
person entities, we'd need to have unique topic ids for each one. For example,
we could have a topic id "person/123", where "123" would be unique to each person.
In that case the same `CollaborationAvatarGroup` component could be reused for
editing different persons by changing the topic with the `setTopic` method.

==== Add Field Collaboration

To enable collaboration with the text field and date picker components, we'll use a class called
`CollaborationBinder`. It extends the functionality of the `Binder` class, which
binds values between Java beans and Vaadin field components.
Visit https://vaadin.com/docs/v14/flow/binding-data/tutorial-flow-components-binder.html[the Vaadin docs site] to learn more about the binder.

To initialize a collaboration binder, we need to provide the type that will be
edited, as well as the local user's information.
After initializing, we use the regular binder methods to bind
the person object's name property to our text field component,
and the date of birth property to our date picker component.

Finally, we set the topic to connect to (the same as for `CollaborationAvatarGroup`)
and a supplier for the initial bean value that will populate the
fields when the first user connects to the topic. The supplier could load the
editable item from a backend, but in this example we populate the fields with an empty
`Person` object.

[source, java]
----
CollaborationBinder<Person> binder = new CollaborationBinder<>(
        Person.class, localUser);
binder.forField(nameField).bind("name");
binder.forField(dateOfBirthField).bind("dateOfBirth");
binder.setTopic("tutorial", () -> new Person());
----

This piece of code takes care of propagating the field values among users,
as well as displaying the currently focused user with the field highlight.

[[ce.tutorial.run]]
=== Run the Application
* Follow instructions in the application's `README.md` file to start the application.
The exact steps depend on the chosen tech stack.
* Open http://localhost:8080/ in multiple browser tabs and test the app: notice the avatars,
focus the fields and notice the field highlight, enter new values and notice how the fields
update in the other tabs
